name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: build
    runs-on: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Check flake
        # A 'packages' entry will get generated for more systems than the derivation supports
        run: NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nix flake check --impure

      - name: Build flake
        run: nix build

