name: update-flake-lock

on:
  repository_dispatch:
  schedule:
    - cron: '13 05 12 * *' # At 05:13 the 12th every month

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v14
        with:
          pr-title: "Update flakes lock"
          pr-labels: ci
